"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import mongoengine

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '141(%v()6^sj-qb-!0=7pccuxy(%1t*x2cc6vc5@-6qarpq($d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
APPEND_SLASH = True
ALLOWED_HOSTS = ['10.169.210.178','100.106.209.205','10.186.87.54','polestar.huawei.com','100.106.240.217','100.106.241.150','127.0.0.1','10.142.103.92','5g.rnd.huawei.com','100.106.192.175','100.106.160.237','localhost','10.151.68.161']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'HWuser',
    'item',
    'daily',
    'product',
    'project',
    'bug',
    'dailyrelease',
    'markinfo',
    'checkin',
    'rest_framework',
    'rollrelease',
    'usr_commit',
    'sms_msg',
    'basic_quality',
    'api',
    'build_codebase_info',
    'ci',
    'feedback',
    'mml',
    'visit',
    'server',
    'code_quality',
    'server_monitor',
    'performance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'visit.VisitMiddleware.IncreaseVisit',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(__file__), 'templates').replace('\\','/'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'common.context_processors.template_variable'
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'webtest',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '100.106.240.217',
        'PORT': '3306',
    },
    'cid': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'webtest',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '100.106.240.217',
        'PORT': '3306',
    },
    'checkin': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'commit_info',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '100.106.240.217',
        'PORT': '3306',
    },
	'bug': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Bug',
        'USER': 'root',
        'PASSWORD': 'rncbam',
        'HOST': '10.177.155.206',
        'PORT': '3306',
    },
    'db_showdata':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'l3_performance',
        'USER': 'root',
        'PASSWORD': 'CID0password',
        'HOST': '100.106.230.137',
        'PORT': '3306',
    }
}

mongoengine.connect(db='test',alias='mongodb', host='mongodb://100.107.241.230:27017,100.107.241.232:27017',replicaSet='5G_WEB')



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s, %(name)s, %(filename)s, %(lineno)d, %(levelname)s, %(message)s'
        },
    },
    'filters': {
    },
    'handlers': {
        'default': {
            'level':'DEBUG',
            'class':'HWuser.mhandlers.MRotatingFileHandler',
            'filename': os.path.join(os.path.dirname(__file__), 'log/', 'request.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 5,
            'formatter':'standard',
        },
    },
    'loggers': {
        'request': {
            'handlers': ['default'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(os.path.dirname(__file__), '../static/'),)

BASE_DIR = os.path.dirname(__file__)
CONFIG_DIR = '%s/config' % (BASE_DIR)
CONFIG_FILE = ['LanguageConfig.ini', 'SystemConfig.ini', 'Enumconfig.ini']
TEAM_LIST = ['EE','eSMP','HIM','CSS','NET','FSP','SIGMA']


# print(CONFIG_DIR)
# print(11)
